name: "Notebook actions"
description: "Convert Jupyter notebooks to html"
author: "Travis Ormsby"

inputs:
  CHANGED_FILES:
    description: "Space delimited list of changed files in the commit"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
