name: "Notebook actions"
description: "Convert Jupyter notebooks to html"
author: "Travis Ormsby"

inputs:
  NOTEBOOKS:
    description: "Notebooks to convert"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
