name: "Notebook actions"
description: "Convert Jupyter notebooks to html"
author: "Travis Ormsby"

inputs:
  CHANGED_FILES:
    description: "Space delimited list of changed files in the commit"
    required: true

outputs:
  CHANGED_HTML:
    description: "Space delimited list of updated html files from notebook converstion"
    value: ${{ steps.nbconvert.outputs.CHANGED_HTML}}


runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
