name: A workflow to convert Jupyter Notebooks to html
on:
  push:
    paths:
      - '**.ipynb'
jobs:
  build:
    name: nbconvert action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
      - uses: ./action-a
        with:
          CHANGED_FILES: ${{ steps.files.outputs.all }}
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: html update bot
          message: "Update html"
          add: "test1.html"
