name: A workflow to convert Jupyter Notebooks to html
on:
  push:
    paths:
      - '**.ipynb'
jobs:
  build:
    name: nbconvert action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./action-a
        with:
          NOTEBOOKS: "Lesson1.ipynb"
