name: A workflow to convert Jupyter Notebooks to html
# Trigger whenever a Jupyter Notebook file is pushed to the repo
on:
  push:
    paths:
      - '**.ipynb'
jobs:
  build:
    name: nbconvert action
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Get changed files
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Convert notebooks with Docker
        id: nbconvert
        uses: ./action-a
        with:
            CHANGED_FILES: ${{ steps.files.outputs.all }}
      - name: Add and commit converted notebooks
        uses: EndBug/add-and-commit@v7
        with:
          message: "Update html"
          add: ${{ steps.nbconvert.outputs.CHANGED_HTML }}
