name: A workflow to convert Jupyter Notebooks to html
on:
  push:
    paths:
      - '**.ipynb'
jobs:
  build:
    name: nbconvert action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: python -m pip install jupyter nbconvert nbformat
      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ $changed_file == *.ipynb ]]; then
              jupyter nbconvert --template=collapsible_headings --to html_ch $changed_file
            fi
          done
      - uses: EndBug/add-and-commit@v7
        with:
          author_name: "html update bot"
          message: "Update html"
          add: "test1.html"
